Feature/add walks
yannhn/capstone-project pull request #35
Opened 2022-07-03 15:52 UTC by yannhn

2022-07-03 18:55 UTC, Quaquaro reviewed
Very well structured project. Just made you a few comments. Have fun with the bootcamp.

2022-07-03 18:55 UTC, Quaquaro commented on src/components/InputWalk/index.js
> +					<h4>Your walks</h4>
Perhaps an h3 as container heading would be better here

2022-07-03 18:55 UTC, Quaquaro commented on src/components/InputWalk/index.js
> +							<input
You could think about building in a separate input component for this.
`export default function Input ({name, labelText ...props}) {
	<label htmlFor={name}>labelText</label>
	<input name={name} id={name} {...props}/>
}`

Also, I would recommend that you pull the input element out of the label.

2022-07-03 18:55 UTC, Quaquaro commented on src/components/InputWalk/styled.js
> +	h4 {
Since you center the text of your form with text-align center, you do not need display flex and justify-content here.

2022-07-03 18:55 UTC, Quaquaro commented on src/components/InputWalk/styled.js
> +	}
I would recommend setting a margin-top for the add button.

2022-07-04 08:50 UTC, stefankorder requested changes
Good work! Please take a look at my and @Quaquaro Suggestions.

2022-07-04 08:50 UTC, stefankorder commented on src/components/InputWalk/styled.js
> +	section {
I would recommend you to create more separte styled components, instead to rule the styling of the child tags inside the parent styled component. This could create problems if you change your DOM structure in future.

2022-07-04 21:41 UTC, yannhn commented on src/components/InputWalk/index.js
> +							<input
Thanks for the feedback! I planned to restructure my code to make more use of reusable form-components. I have different forms on my homepage and will look into that as soon they are all finished (which should be hopefully tomorrow).

2022-07-04 21:47 UTC, yannhn commented
Thanks @stefankorder and @Quaquaro for your feedback! Really appreciate it! I already implemented it. If you don't mind please take another look at it.

2022-07-05 07:26 UTC, stefankorder approved these changes
👍🏻

2022-07-05 07:47 UTC, merged